# ============================================================
# config.py — Shared configuration for both Ego and RSU Pis
# ============================================================
# SETUP INSTRUCTIONS:
#   1. Find Pi 1 (Ego) IP:  run `hostname -I` on Pi 1
#   2. Find Pi 2 (RSU) IP:  run `hostname -I` on Pi 2
#   3. Update EGO_IP and RSU_IP below
#   4. Both Pis must be on the same WiFi network
# ============================================================

# --- Network ---
EGO_IP       = "192.168.1.100"   # Pi 1 (Ego) — RSU sends everything HERE
RSU_IP       = "192.168.1.101"   # Pi 2 (RSU) — for reference only
UDP_PORT     = 5005              # RSU → Ego: detection JSON
RSU_FRAME_PORT = 5006            # RSU → Ego: compressed camera frame (JPEG)

# --- Model ---
# Use "yolov8n.pt" for first-run testing (downloads automatically)
# Use "yolov8n_ncnn_model" after running export_model.py on a PC (faster on Pi)
MODEL_PATH = "yolov8n.pt"

# --- Camera ---
CAMERA_INDEX  = 0       # 0 = default camera / Pi Camera Module
FRAME_WIDTH   = 640
FRAME_HEIGHT  = 480

# --- Detection ---
CONFIDENCE_THRESHOLD = 0.40

# --- Frame streaming (RSU → Ego) ---
# Lower quality = smaller packet = less likely to exceed UDP limit (65535 bytes)
JPEG_QUALITY = 40

# --- Homography calibration ---
# Generated by calibrate.py — maps RSU image coordinates → Ego image coordinates
HOMOGRAPHY_FILE = "homography.npy"

# --- Display (Ego main monitor) ---
# 3-panel layout: [Ego cam | RSU cam | Fused ego view]
DIVIDER_WIDTH  = 6
PANEL_WIDTH    = FRAME_WIDTH                       # each panel = camera frame width
DISPLAY_WIDTH  = PANEL_WIDTH * 3 + DIVIDER_WIDTH * 2
DISPLAY_HEIGHT = FRAME_HEIGHT

# RSU detection is considered stale after this many seconds
RSU_TIMEOUT_SEC = 2.0

# Classes that trigger a critical flashing warning when hidden from ego
CRITICAL_CLASSES = {"person", "bicycle", "motorcycle"}
